# Generated by Django 4.2.7 on 2023-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ips',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ips',
            field=models.ManyToManyField(to='home.ipaddress'),
        ),
    ]
