# Generated by Django 4.2.7 on 2023-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ipaddress_remove_userprofile_ips_userprofile_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ips',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ips',
            field=models.TextField(blank=True),
        ),
    ]
